# Generated by Django 2.2.2 on 2019-06-30 18:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.IntegerField(blank=True)),
                ('category', models.CharField(default='Creator', max_length=10)),
                ('date_of_joining', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('image', models.ImageField(default='profile_images/default.png', upload_to='profile_images/')),
            ],
        ),
        migrations.CreateModel(
            name='winners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_name', models.CharField(max_length=255)),
                ('winner_email', models.CharField(max_length=255)),
                ('winner_image', models.ImageField(blank=True, default='winners/default.png', upload_to='winners/')),
                ('rank', models.IntegerField()),
                ('giveaway_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='new_giveaway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giveaway_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('giveaway_name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=2250)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('banner_image', models.ImageField(default='banner/default.png', upload_to='banner/')),
                ('image1', models.ImageField(default='sideimages/default1.png', upload_to='sideimages/')),
                ('image2', models.ImageField(default='sideimages/default2.png', upload_to='sideimages/')),
                ('image3', models.ImageField(default='sideimages/default3.png', upload_to='sideimages/')),
                ('number_of_winners', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.user_details')),
            ],
        ),
    ]
