# Generated by Django 2.2.2 on 2019-06-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20190630_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
