# Generated by Django 2.2.2 on 2019-06-30 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_auto_20190630_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_giveaway',
            old_name='giveaway_name',
            new_name='giveaway_title',
        ),
        migrations.AlterField(
            model_name='winners',
            name='giveaway_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.new_giveaway'),
        ),
        migrations.CreateModel(
            name='giveaway_rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField()),
                ('insta_profile_follow', models.URLField(blank=True)),
                ('insta_post', models.URLField(blank=True)),
                ('insta_comment', models.URLField(blank=True)),
                ('facebook_profile_like', models.URLField(blank=True)),
                ('facebook_post_like', models.URLField(blank=True)),
                ('facebook_post_comment', models.URLField(blank=True)),
                ('facebook_post_share', models.URLField(blank=True)),
                ('twitter_profile_follow', models.URLField(blank=True)),
                ('tweet_like', models.URLField(blank=True)),
                ('tweet_comment', models.URLField(blank=True)),
                ('retweet', models.URLField(blank=True)),
                ('youtube_subscibe', models.URLField(blank=True)),
                ('youtube_comment', models.URLField(blank=True)),
                ('youtube_like', models.URLField(blank=True)),
                ('youtube_share', models.URLField(blank=True)),
                ('go_to_this_link', models.URLField(blank=True)),
                ('giveaway_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.new_giveaway')),
            ],
        ),
    ]
