# Generated by Django 2.2.2 on 2019-06-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_auto_20190630_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway_rule',
            name='giveaway_id',
            field=models.UUIDField(default='c0b89d2e-cb31-47ec-b175-a0ee9e59d433'),
        ),
        migrations.AddField(
            model_name='winners',
            name='giveaway_id',
            field=models.UUIDField(default='c0b89d2e-cb31-47ec-b175-a0ee9e59d433'),
        ),
    ]
