# Generated by Django 2.2.2 on 2019-06-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_auto_20190630_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_giveaway',
            name='image1',
            field=models.ImageField(blank=True, default='sideimages/default1.png', upload_to='sideimages/'),
        ),
        migrations.AlterField(
            model_name='new_giveaway',
            name='image2',
            field=models.ImageField(blank=True, default='sideimages/default2.png', upload_to='sideimages/'),
        ),
        migrations.AlterField(
            model_name='new_giveaway',
            name='image3',
            field=models.ImageField(blank=True, default='sideimages/default3.png', upload_to='sideimages/'),
        ),
    ]
