# Generated by Django 2.2.2 on 2019-06-30 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_auto_20190630_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway_rule',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='details.user_details'),
        ),
    ]
