# Generated by Django 2.2.2 on 2019-07-01 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('details', '0010_auto_20190701_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='giveaway_analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giveaway_id', models.UUIDField(default='c0b89d2e-cb31-47ec-b175-a0ee9e59d433')),
                ('participants_count', models.IntegerField(default=0)),
                ('completed', models.IntegerField(default=0)),
                ('partial', models.IntegerField(default=0)),
                ('giveaway_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.new_giveaway')),
            ],
        ),
        migrations.CreateModel(
            name='entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giveaway_id', models.UUIDField(default='c0b89d2e-cb31-47ec-b175-a0ee9e59d433')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BinaryField(default=False)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
