# Generated by Django 2.2.2 on 2019-07-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0011_entry_giveaway_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveaway_analytics',
            name='giveaway_name',
            field=models.CharField(max_length=255),
        ),
    ]
