# Generated by Django 2.2.2 on 2019-07-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0012_auto_20190701_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveaway_rule',
            name='giveaway_name',
            field=models.CharField(max_length=255),
        ),
    ]
