# Generated by Django 2.2.2 on 2019-07-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0013_auto_20190701_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
