# Generated by Django 2.2.2 on 2019-07-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0014_auto_20190701_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
