# Generated by Django 2.2.2 on 2019-07-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0015_auto_20190701_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='giveaway_title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
