# Generated by Django 2.2.2 on 2019-07-01 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0016_entry_giveaway_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='username',
            new_name='user',
        ),
    ]
