# Generated by Django 2.2.2 on 2019-07-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0017_auto_20190701_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway_rule',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
