# Generated by Django 2.2.2 on 2019-07-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0018_giveaway_rule_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_giveaway',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
