# Generated by Django 2.2.2 on 2019-07-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0019_auto_20190704_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveaway_rule',
            name='facebook_post_comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='giveaway_rule',
            name='facebook_post_like',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='giveaway_rule',
            name='facebook_post_share',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='giveaway_rule',
            name='facebook_profile_like',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='giveaway_rule',
            name='go_to_this_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='giveaway_rule',
            name='insta_comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='giveaway_rule',
            name='insta_post',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='giveaway_rule',
            name='insta_profile_follow',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='giveaway_rule',
            name='retweet',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='giveaway_rule',
            name='tweet_comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='giveaway_rule',
            name='tweet_like',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='giveaway_rule',
            name='twitter_profile_follow',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='giveaway_rule',
            name='youtube_comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='giveaway_rule',
            name='youtube_like',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='giveaway_rule',
            name='youtube_share',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='giveaway_rule',
            name='youtube_subscibe',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
