# Generated by Django 2.2.3 on 2019-07-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0021_giveaway_rule_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('comment', models.CharField(blank=True, max_length=5500)),
                ('url', models.CharField(max_length=500)),
            ],
        ),
    ]
