# Generated by Django 2.2.3 on 2019-07-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0023_auto_20190716_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(blank=True, max_length=5500),
        ),
    ]
