# Generated by Django 2.2.3 on 2019-07-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0025_comments_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
