# Generated by Django 2.2.3 on 2019-07-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0027_comments_video_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='video_count',
            field=models.IntegerField(default=0),
        ),
    ]
