# Generated by Django 2.2.3 on 2019-07-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0028_auto_20190718_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='video_freq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='comments',
            name='video_count',
        ),
    ]
